# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate cpl  # or change the name: cpl and activate that name

name: cpl

channels:
  - conda-forge
  - default
dependencies:
  - python=3.9

# Scientific libraries
  - numpy<=1.23.5 # to avoid conflicts with numba
  - numba
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - datashader
  - tifffile
  - statsmodels
  - pyqt=5
  - pyqtgraph
  - pyopenssl
  - pyqt-stubs
  - vispy
  - umap-learn

# Image and IO
  - pillow
  - Opencv
  - openpyxl
  - OpenSSL
  - pytables
  - openblas
  - pip

# For type annotations
  - black

# Documentation
  - sphinx=6.2.1
  - sphinx-design
  - pydata-sphinx-theme=0.13.3
  - numpydoc=1.4.0

  - icecream # debugging

  - pip:
    - sonpy
    - termcolor
    - psutil
    - easygui
    - prompt_toolkit
    - setuptools~=69.0.3

