# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate spk2py-dev

name: spk2extract
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9

# Scientific libraries
  - numpy<=1.23.5 # to avoid conflicts with numba
  - numba
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - datashader
  - pyqt=5
  - pyqtgraph
  - pyopenssl
  - pyqt-stubs

# Image and IO
  - h5py
  - pillow
  - Opencv
  - openpyxl
  - OpenSSL

# Compilation
  - compilers
  - openblas
  - pip
  - spin

# For type annotations
  - typing_extensions>=4.2.0
  - mypy=1.5.1
  - black

# Documentation
  - sphinx=6.2.1
  - sphinx-design
  - pydata-sphinx-theme=0.13.3
  - numpydoc=1.4.0

  - pip:
    - sonpy
    - termcolor
